[book]
authors = ["Abdulla Abdurakhmanov"]
language = "en"
multilingual = false
src = "src"
title = "Slack Morphism for Rust"
description = "Slack Morphism is a type-safe and modern client for Rust"

[rust]
edition = "2018"

[build]
build-dir = "output"
create-missing = false
