[package]
name = "slack-morphism-client"
version = "0.1.0"
authors = ["Abdulla Abdurakhmanov <abdulla@latestbit.com>"]
edition = "2018"

[lib]
name = "slack_morphism_client"
path = "src/lib.rs"

[dependencies]
slack-morphism-models = { path = "../models", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.4"
rvstruct = "0.2"
rsb_derive = "0.2"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
hyper-tls = "0.4"
url = "2.1"
mime = "0.3"
futures = "0.3"
futures-util = "0.3"
bytes = "0.5"
base64 = "0.12"
hex = "0.4"
log = "0.4"
ring = "0.16"